### ISSUE TITLE
ChunkedEncodingError: Connection broken: InvalidChunkLength

### ISSUE THREAD

**Issue by GorgiAstro** [StenSipma/astrometry_net_client#31] opened 2022-11-02 16:40 UTC
Hi there,
This client is nice!
However when trying it, I ran into the following issue (see traceback below).

I am using the library version 0.2.7 in a Jupyter notebook in Ubuntu, with Python 3.10, urllib3 1.26.12 and requests 2.28.1.

My code is the following:
```
from astrometry_net_client import Session, FileUpload

s = Session(api_key=api_key)

upl = FileUpload(os.path.join(pic_folder, current_pic), session=s)
submission = upl.submit()    
submission.until_done() 
job = submission.jobs[0]    
job.until_done()        
if job.success():
    wcs = job.wcs_file()   
print(job.info())     
```
Where `api_key` is valid, and `pic_folder` and `current_pic` exist. I checked on astrometry.net, the picture is successfully uploaded, a job is created, and a couple of minutes later on the website I can see that the star solving was successful. So the issue is somewhere in the response from astrometry.net, but I couldn't find out what is the issue exactly.

Thanks in advance!

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/urllib3/response.py:748, in HTTPResponse._update_chunk_length(self)
    747 try:
--> 748     self.chunk_left = int(line, 16)
    749 except ValueError:
    750     # Invalid chunked protocol response, abort.

ValueError: invalid literal for int() with base 16: b'\xf9\xf1Bf\x91\x00\x00\x00'

During handling of the above exception, another exception occurred:

InvalidChunkLength                        Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/urllib3/response.py:443, in HTTPResponse._error_catcher(self)
    442 try:
--> 443     yield
    445 except SocketTimeout:
    446     # FIXME: Ideally we'd like to include the url in the ReadTimeoutError but
    447     # there is yet no clean way to get at it from this context.

File ~/.local/lib/python3.10/site-packages/urllib3/response.py:815, in HTTPResponse.read_chunked(self, amt, decode_content)
    814 while True:
--> 815     self._update_chunk_length()
    816     if self.chunk_left == 0:

File ~/.local/lib/python3.10/site-packages/urllib3/response.py:752, in HTTPResponse._update_chunk_length(self)
    751 self.close()
--> 752 raise InvalidChunkLength(self, line)

InvalidChunkLength: InvalidChunkLength(got length b'\xf9\xf1Bf\x91\x00\x00\x00', 0 bytes read)

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/requests/models.py:816, in Response.iter_content.<locals>.generate()
    815 try:
--> 816     yield from self.raw.stream(chunk_size, decode_content=True)
    817 except ProtocolError as e:

File ~/.local/lib/python3.10/site-packages/urllib3/response.py:623, in HTTPResponse.stream(self, amt, decode_content)
    622 if self.chunked and self.supports_chunked_reads():
--> 623     for line in self.read_chunked(amt, decode_content=decode_content):
    624         yield line

File ~/.local/lib/python3.10/site-packages/urllib3/response.py:803, in HTTPResponse.read_chunked(self, amt, decode_content)
    798     raise BodyNotHttplibCompatible(
    799         "Body should be http.client.HTTPResponse like. "
    800         "It should have have an fp attribute which returns raw chunks."
    801     )
--> 803 with self._error_catcher():
    804     # Don't bother reading the body of a HEAD request.
    805     if self._original_response and is_response_to_head(self._original_response):

File ~/miniconda3/envs/tubix20/lib/python3.10/contextlib.py:153, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    152 try:
--> 153     self.gen.throw(typ, value, traceback)
    154 except StopIteration as exc:
    155     # Suppress StopIteration *unless* it's the same exception that
    156     # was passed to throw().  This prevents a StopIteration
    157     # raised inside the "with" statement from being suppressed.

File ~/.local/lib/python3.10/site-packages/urllib3/response.py:460, in HTTPResponse._error_catcher(self)
    458 except (HTTPException, SocketError) as e:
    459     # This includes IncompleteRead.
--> 460     raise ProtocolError("Connection broken: %r" % e, e)
    462 # If no exception is thrown, we should avoid cleaning up
    463 # unnecessarily.

ProtocolError: ("Connection broken: InvalidChunkLength(got length b'\\xf9\\xf1Bf\\x91\\x00\\x00\\x00', 0 bytes read)", InvalidChunkLength(got length b'\xf9\xf1Bf\x91\x00\x00\x00', 0 bytes read))

During handling of the above exception, another exception occurred:

ChunkedEncodingError                      Traceback (most recent call last)
Cell In [6], line 7
      5 upl = FileUpload(os.path.join(pic_folder, current_pic), session=s)
      6 submission = upl.submit()    
----> 7 submission.until_done() 
      8 job = submission.jobs[0]    
      9 job.until_done(timeout=timeout)        

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/astrometry_net_client/statusables.py:224, in Statusable.until_done(self, start, end, timeout)
    222 log.debug(log_msg.format(sleep_time, timeout))
    223 while timeout is None or now() - start_time < timeout:
--> 224     response = self.status()
    225     log.debug("Current status response: {}".format(response))
    227     if self.done():

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/astrometry_net_client/statusables.py:155, in Statusable.status(self, force)
    153     log_msg = "Statusable {} not done, querying status..."
    154     log.debug(log_msg.format(self.__class__.__name__))
--> 155     self.stat_response = self._make_status_request()
    157 return self.stat_response

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/astrometry_net_client/statusables.py:325, in Submission._make_status_request(self)
    323 def _make_status_request(self):
    324     r = Request(self.url)
--> 325     response = r.make()
    326     self.response = response
    328     # TODO verify which of these entries are valid in the response

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/astrometry_net_client/request.py:141, in Request.make(self)
    127 def make(self) -> Union[dict, bytes]:
    128     """
    129     Send the actual request to the API.
    130     returns the response
   (...)
    139         but also a binary file (e.g. when expecting a filts file).
    140     """
--> 141     return self._make_request()

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/astrometry_net_client/request.py:87, in Request._make_request(self)
     84 payload = {"request-json": json.dumps({**self.data, **self.settings})}
     86 log.debug("Sending {!r} with payload {}".format(self, payload))
---> 87 response = self.method(self.url, data=payload, **self.arguments)
     88 log.debug("Retrieved response: {}".format(response.text))
     90 self.original_response = response

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/requests/api.py:73, in get(url, params, **kwargs)
     62 def get(url, params=None, **kwargs):
     63     r"""Sends a GET request.
     64 
     65     :param url: URL for the new :class:`Request` object.
   (...)
     70     :rtype: requests.Response
     71     """
---> 73     return request("get", url, params=params, **kwargs)

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/requests/api.py:59, in request(method, url, **kwargs)
     55 # By using the 'with' statement we are sure the session is closed, thus we
     56 # avoid leaving sockets open which can trigger a ResourceWarning in some
     57 # cases, and look like a memory leak in others.
     58 with sessions.Session() as session:
---> 59     return session.request(method=method, url=url, **kwargs)

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/requests/sessions.py:587, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    582 send_kwargs = {
    583     "timeout": timeout,
    584     "allow_redirects": allow_redirects,
    585 }
    586 send_kwargs.update(settings)
--> 587 resp = self.send(prep, **send_kwargs)
    589 return resp

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/requests/sessions.py:745, in Session.send(self, request, **kwargs)
    742         pass
    744 if not stream:
--> 745     r.content
    747 return r

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/requests/models.py:899, in Response.content(self)
    897         self._content = None
    898     else:
--> 899         self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
    901 self._content_consumed = True
    902 # don't need to release the connection; that's been handled by urllib3
    903 # since we exhausted the data.

File ~/miniconda3/envs/tubix20/lib/python3.10/site-packages/requests/models.py:818, in Response.iter_content.<locals>.generate()
    816     yield from self.raw.stream(chunk_size, decode_content=True)
    817 except ProtocolError as e:
--> 818     raise ChunkedEncodingError(e)
    819 except DecodeError as e:
    820     raise ContentDecodingError(e)

ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'\\xf9\\xf1Bf\\x91\\x00\\x00\\x00', 0 bytes read)", InvalidChunkLength(got length b'\xf9\xf1Bf\x91\x00\x00\x00', 0 bytes read))
```

**Comment by StenSipma** [comment] 2022-11-02 16:46
Thanks for trying it out! I don't see the immediate solution to this, but I am curious what file you are trying to upload. I have mainly been testing this with FITS files, so maybe other files behave less nicely?

**Comment by GorgiAstro** [comment] 2022-11-02 17:11
Thanks for the swift response! 

This is the test picture in PNG format, it was taken from our satellite: https://nova.astrometry.net/user_images/6685335#annotated

Btw I also tried successfully sending this picture to astrometry.net via the `astroquery` python library (which I guess also uses requests).

I also tried converting the PNG picture to FITS using GIMP, but I still get the same error message.

**Comment by StenSipma** [comment] 2022-11-02 17:46
I just checked with some other submissions and it indeed seems to be a general problem with the client at the moment, I will look into it!

**Comment by StenSipma** [comment] 2022-11-02 19:15
Okay, I believe the issue is fixed with the latest version. Please upgrade the package with
```
pip install --upgrade astrometry-net-client
```
and see if it works now. If you run into any other issues, or you have any suggestions let me know :)

**Closed as completed by StenSipma** 2022-11-02 19:15 UTC

**Comment by GorgiAstro** [comment] 2022-11-02 19:37
That solved it, thanks a lot for the faster-than-light response!
